TransferMarket.App/ViewModels/PlayerViewModel.cs
namespace TransferMarket.App.ViewModels
{
    public class PlayerViewModel
    {
        public string Name { get; set; }
        public DateTime Birthday { get; set; }
        public string Team { get; set; }
        public string Amplification { get; set; }
        public decimal Price { get; set; }
        public int Games { get; set; }
        public int Goals { get; set; }
        public int YellowCards { get; set; }
        public int RedCards { get; set; }
    }
}

TransferMarket.App/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using TransferMarket.App.Services;

namespace TransferMarket.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGameRepository _gameRepository;

        public HomeController(IGameRepository gameRepository)
        {
            _gameRepository = gameRepository;
        }

        public IActionResult Index()
        {
            var games = _gameRepository.GetAll();

            return View(games);
        }
    }
}

TransferMarket.App/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using TransferMarket.App.Services;
using TransferMarket.App.ViewModels;
using TransferMarket.Data;

namespace TransferMarket.App.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IPlayerRepository _playerRepository;
        private readonly IGameRepository _gameRepository;
        private readonly ICardRepository _cardRepository;

        public PlayerController(IPlayerRepository playerRepository, IGameRepository gameRepository, ICardRepository cardRepository)
        {
            _playerRepository = playerRepository;
            _gameRepository = gameRepository;
            _cardRepository = cardRepository;
        }

        public IActionResult Index()
        {
            var players = _playerRepository.GetAll();

            return View(players);
        }

        public IActionResult Details(int id)
        {
            var player = _playerRepository.GetById(id);
            if (player == null)
            {
                return NotFound();
            }
            var games = _gameRepository.GetAll().ToList().FindAll(x => x.HomeTeamId == player.TeamId || x.GuestTeamId == player.TeamId);
            var cards = _cardRepository.GetAll().ToList().FindAll(x => x.PlayerId == player.Id);

            var viewModel = new PlayerViewModel
            {
                Name = player.Name,
                Team = player.Team.Name,
                Birthday = player.Birthday,
                Amplification = player.Amplification.Name,
                Price = player.Price,
                Games = games.Count,
                YellowCards = cards.Select(x => x.CardType.Name == "Желтая" || x.CardType.Name == "Вторая желтая").ToList().Count,
                RedCards = cards.Select(x => x.CardType.Name == "Красная").ToList().Count
            };
            foreach (var game in games)
            {
                viewModel.Goals += game.ScoredGoals.Select(x => x.PlayerScoredId == player.Id).ToList().Count;
            }

            return View(viewModel);
        }

        public IActionResult Create()
        {
            return View("Update", new Player());
        }

        public IActionResult Update(int? id)
        {
            if (id is null) 
            {
                return View(new Player());
            }

            var player = _playerRepository.GetById((int)id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        [HttpPost]
        public IActionResult Update(Player model)
        {
            if (model.Id == 0)
            {
                var id = _playerRepository.Create(model);
                return RedirectToAction("Details", new { id });
            }

            if (!_playerRepository.Update(model))
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var player = _playerRepository.GetById(id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            if (!_playerRepository.Delete(id))
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
    }
}

TransferMarket.App/Controllers/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using TransferMarket.App.Services;
using TransferMarket.App.Services.Impl;
using TransferMarket.Data;

namespace TransferMarket.App.Controllers
{
    public class TeamController : Controller
    {
        private readonly ITeamRepository _teamRepository;

        public TeamController(ITeamRepository teamRepository)
        {
            _teamRepository = teamRepository;
        }

        public IActionResult Index()
        {
            var teams = _teamRepository.GetAll();

            return View(teams);
        }

        public IActionResult Details(int id)
        {
            var team = _teamRepository.GetById(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        public IActionResult Create()
        {
            return View("Update", new Team());
        }

        public IActionResult Update(int? id)
        {
            if (id is null)
            {
                return View(new Team());
            }

            var team = _teamRepository.GetById((int)id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        [HttpPost]
        public IActionResult Update(Team model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.Id == 0)
            {
                var id = _teamRepository.Create(model);
                return RedirectToAction("Details", new { id });
            }

            if (!_teamRepository.Update(model))
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var team = _teamRepository.GetById(id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            if (!_teamRepository.Delete(id))
            {
                return NotFound();
            }

            return RedirectToAction("Index");
        }
    }
}

TransferMarket.App/Views/Home/Index.cshtml
@model IEnumerable<Game>
@{
    ViewBag.Title = "Главная";
}

@if (Model.Any())
{
    @foreach (var game in Model)
    {
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td width="40%">
                        <a asp-controller="Team" asp-action="Details" asp-route-id="@game.HomeTeam.Id">@game.HomeTeam.Name</a>
                    </td>
                    <td width="20%">
                        @(game.ScoredGoals.ToList().FindAll(x => x.PlayerScored.TeamId == game.HomeTeamId).Count) - @(game.ScoredGoals.ToList().FindAll(x => x.PlayerScored.TeamId == game.GuestTeamId).Count)
                    </td>
                    <td width="40%">
                        <a asp-controller="Team" asp-action="Details" asp-route-id="@game.GuestTeam.Id">@game.GuestTeam.Name</a>
                    </td>
                </tr>
            </tbody>
        </table>
    }
}
else
{
    <p>Матчи отсутствуют</p>
}

TransferMarket.App/Views/Player/Delete.cshtml
@model Player
@{
    ViewData["Title"] = "Удалить данные";
}

<h3>Вы дествительно хотите удалить данные об игроке @Model.Name?</h3>
<hr />

<div>
    <form asp-action="DeleteConfirm" asp-route-id="@Model.Id">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TransferMarket.App/Views/Player/Details.cshtml
@model PlayerViewModel
@{
    ViewData["Title"] = $"{Model.Name} - профиль игрока";
}

<h1>@Model.Name</h1>

<div>
    <h4>Статистика Игрока</h4>
    <hr />
    <dl class="row">
        @{
            //int goals = 0, yellowCards = 0, redCards = 0;
            //foreach (var game in Model.Item2)
            //{
            //    goals += game.ScoredGoals.Select(x => x.PlayerScoredId == Model.Item1.Id).ToList().Count;
            //    yellowCards += game.Cards.Select(x => x.PlayerId == Model.Item1.Id && (x.CardType.Name == "Желтая" || x.CardType.Name == "Желтая")).ToList().Count;
            //    redCards += game.Cards.Select(x => x.PlayerId == Model.Item1.Id && x.CardType.Name == "Красная").ToList().Count;
            //}
        }
        <dt class="col-sm-2">
            Игры
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games)
        </dd>

        <dt class="col-sm-2">
            Голы
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Goals)
        </dd>

        <dt class="col-sm-2">
            Желтые карточки
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.YellowCards)
        </dd>

        <dt class="col-sm-2">
            Красные карточки
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RedCards)
        </dd>
    </dl>
</div>

<div>
    <h4>Данные игрока</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            Дата рождения
        </dt>
        <dd class="col-sm-10">
            @{
                var birthday = Model.Birthday.ToString("d");
            }
            @Html.DisplayFor(model => birthday)
        </dd>

        <dt class="col-sm-2">
            Амплуа
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Amplification)
        </dd>

        <dt class="col-sm-2">
            Нынешний клуб
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Team)
        </dd>
    </dl>
</div>

TransferMarket.App/Views/Player/Index.cshtml
@model IEnumerable<Player>
@{
    ViewBag.Title = "Игроки";
}

<a class="btn btn-dark" asp-action="Create">Создать</a>

<hr />

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Имя</th>
                <th>Клуб</th>
                <th>Стоимость</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var player in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Delete" asp-route-id="@player.Id" class="text-danger">
                            <i class="fa fa-trash-alt"></i>
                        </a>
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@player.Id">@player.Name</a>
                    </td>
                    <td>@player.Team!.Name</td>
                    <td>@Math.Round(player.Price, 2) млн €</td>
                    <td>
                        <a asp-action="Update" asp-route-id="@player.Id">
                            <i class="fa fa-user-edit"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Игроков нет</p>
}

TransferMarket.App/Views/Player/Update.cshtml
@model Player
@{
    ViewData["Title"] = "Редактирование";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">

            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Team" class="control-label"></label>
                <input asp-for="Team.Name" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Amplification" class="control-label"></label>
                <input asp-for="Amplification.Name" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TransferMarket.App/Views/Shared/Partial/_Footer.cshtml
<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TransferMarket
        </div>
    </footer>

TransferMarket.App/Views/Shared/Partial/_Header.cshtml
<header>
    <partial name="Partial/_MainMenu" />
</header>

TransferMarket.App/Views/Shared/Partial/_MainMenu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TransferMarket</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Клубы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Игроки</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

TransferMarket.App/Views/Shared/Partial/_Scripts.cshtml
<script src="~/lib/jquery/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/font-awesome/js/all.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

TransferMarket.App/Views/Shared/Partial/_Styles.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

TransferMarket.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <partial name="Partial/_Styles" />

    @await RenderSectionAsync("Styles", false)
</head>
<body>
    <partial name="Partial/_Header" />
    <div class="container">
        @RenderBody()
    </div>
    <partial name="Partial/_Footer" />
    <partial name="Partial/_Scripts" />

    @await RenderSectionAsync("Scripts", false)
</body>
</html>

TransferMarket.App/Views/Team/Details.cshtml
@model Team
@{
    ViewData["Title"] = $"{Model.Name} - профиль клуба";
}

<h1>@Model.Name</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            Общая стоимость
        </dt>
        <dd class="col-sm-10">
            @{
                var totalCost = Math.Round(Model.TotalCost, 2);
            }
            @Html.DisplayFor(model => totalCost) млн €
        </dd>
    </dl>
    <hr />
</div>

@if (Model.Players.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Имя</th>
                <th>Дата рождения</th>
                <th>Стоимость</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var player in Model.Players.OrderBy(x => x.AmplififcationId))
            {
                <tr>
                    <td>
                        <a asp-controller="Player" asp-action="Details" asp-route-id="@player.Id">@player.Name</a>
                    </td>
                    <td>@player.Birthday.ToString("d")</td>
                    <td>@Math.Round(player.Price, 2) млн €</td>
                </tr>
            }
        </tbody>
    </table>
}

TransferMarket.App/Views/Team/Index.cshtml
@model IEnumerable<Team>
@{
    ViewBag.Title = "Клубы";
}

<a class="btn btn-dark" asp-action="Create">Создать</a>

<hr />

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Клуб</th>
                <th>Общая стоимость</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var team in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@team.Id">@team.Name</a>
                    </td>
                    <td>@Math.Round(team.TotalCost, 2) млн €</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Клубов нет</p>
}

TransferMarket.App/Views/Team/Update.cshtml
@model Team
@{
    ViewData["Title"] = "Редактирование";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SeasonId" class="control-label"></label>
                <input asp-for="SeasonId" class="form-control" />
                <span asp-validation-for="SeasonId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TotalCost" class="control-label"></label>
                <input asp-for="TotalCost" class="form-control" />
                <span asp-validation-for="TotalCost" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>